### ISSUE TITLE
[HOLD for payment 2022-10-20] [$250] Feature Request: Set up caching of Jest unit tests in GitHub Actions to speed up PR checks

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10289]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem 
PR checks take longer 

## Solution 
Set up caching of Jest unit tests in GitHub Actions to speed up PR checks

## Workaround:
Unknown 

## Platform:

Where is this issue occurring?

- Web
- iOS
- Android
- Desktop App
- Mobile Web

**Version Number:** 1.1.89-0
**Reproducible in staging?:** 
**Reproducible in production?:** 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:** 
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1659631753442659

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
External Upwork post: https://www.upwork.com/jobs/~01a0c1a1865e60683d
Internal Upwork post: https://www.upwork.com/ab/applicants/1556723707381051392/job-details

**Comment by KingStar1001** [comment]
https://manzoorwani.dev/how-we-brought-down-github-actions-workflow-execution-time-from-20-minutes-to-5-minutes/
This will be helpful for this issue.

**Comment by KingStar1001** [comment]
I have sent proposal on Upwork.

**Comment by roryabraham** [comment]
@KingStar1001 can you also post a proposal in this GitHub issue please?

**Comment by KingStar1001** [comment]
@roryabraham How can I post a proposal in GitHub issue?
kindly tell me how..

**Comment by puneetlath** [comment]
@KingStar1001 you can check out our [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) as well as other issues in the repo to get a sense of how to post a proposal. 

Generally, we're looking for a high-level overview of how you plan to solve the problem. If we like your proposed approach, we'll hire you for the job. Let us know if you have any questions.

**Comment by KingStar1001** [comment]
"Proposal"
Hi Expensify, This is Amine from Upwork.

Solution:
GitHub actions has "build matrix", where where you can create multiple jobs by performing variable substitution in a single job definition.
We can reduce PR time using "build matrix"

**Comment by roryabraham** [comment]
The format for your proposal is fine, but I'm confused how you might use a build matrix to speed up our unit tests. We'll need more details to be able to evaluate the proposal

**Comment by KingStar1001** [comment]
@roryabraham 
These are example about using matrix.
        ...
        name: ${{ matrix.task }}
        ...
            - name: Run ${{ matrix.task }}
              run: yarn ${{ matrix.task }}:ci
Some tasks are run based on matrix.

Also there are other solutions - Improve caching, --changedSince.

**Comment by mzohaibqc** [comment]
*Proposal*
Hi Expensify, This is Zohaib from Upwork.

Solution:
I reviewed your `test.yml` file which runs unit tests and it is simple and runs all test on one instance of github ci container. GitHub actions has feature called *Build Matrix* which allows you to distribute your tasks on multiple instances in parallel/series  to run those tasks independently or based on other tasks. Let's say, you have 100 unit tests which are taking 20 minutes, we can distribute those 100 unit tests to run on 4 instances of github ci containers (tasks) and all tests will complete in around 5 minutes (unless there are some tests which take too much time as compared to other files). We can then combine the test coverage when all tasks are done and upload the coverage where you want to upload.

**Comment by mzohaibqc** [comment]
@rushatgabhane I agree, that is what @KingStar1001 proposed but he did not explain how that will work. Buddy @KingStar1001 no offence to you :)

I can setup jest caching as well if not setup already but main goal is to reduce the PR time which I can ready to help.

**Comment by mzohaibqc** [comment]
@rushatgabhane I already submitted my proposal so I can't attach anything now. However, here are some results.

**Without Matrix**

![withut matrix](https://user-images.githubusercontent.com/13637803/184508932-fec6df02-f205-4fd3-8497-6f546664289a.png)

**With Matrix**
![with matrix](https://user-images.githubusercontent.com/13637803/184508951-ebb673d1-ff2d-4bc3-ac15-1f77935d4c10.png)

**Comment by mzohaibqc** [comment]
@rushatgabhane I already submitted the proposal and can't attach anything now. However, here are some results 

**Without Matrix**
![withut matrix](https://user-images.githubusercontent.com/13637803/184509026-b0200d34-45c2-4c96-b674-7946d828a71c.png)

**With Matrix**
![with matrix](https://user-images.githubusercontent.com/13637803/184509029-d81c3408-eafd-4ccd-af9d-e55a9907b0a6.png)

**Comment by mzohaibqc** [comment]
@rushatgabhane There is nothing much to share related to code. It's everything about github action yml file. However, here is a screenshot of that

![github-action](https://user-images.githubusercontent.com/13637803/184509258-36a0a3f2-7905-46ee-baab-bd0efaece80a.png)

**Comment by mzohaibqc** [comment]
> > github action yml file
> 
> @mzohaibqc yes that's what i'm requesting. And also [caching](https://github.com/Expensify/App/issues/10289#issuecomment-1214213329)

I can start work on this after a short discussion. Just accept the invite on Upwork and start the task.

**Comment by mzohaibqc** [comment]
Hi @rushatgabhane,

Here is proposed solution

I reviewed your test.yml file which runs unit tests and it is simple and runs all test on one instance of github ci container. GitHub actions has feature called Build Matrix which allows you to distribute your tasks on multiple instances in parallel/series to run those tasks independently or based on other tasks. Let's say, you have 100 unit tests which are taking 20 minutes, we can distribute those 100 unit tests to run on 4 instances of github ci containers (tasks) and all tests will complete in around 5 minutes (unless there are some tests which take too much time as compared to other files). We can then combine the test coverage when all tasks are done and upload the coverage where you want to upload.

Goal is to reduce tests execution time which affects PR run time. This solution will reduce this time by splitting tests into multiple jobs and adding/restoring jest cache.

```
name: Unit Tests

on: push

jobs:
  jest:
    runs-on: ubuntu-20.04
    name: jest (job ${{ matrix.chunk }})
    strategy:
      fail-fast: false
      matrix:
        chunk: [0, 1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run Jest Unit Tests
        run: npm run test

      - name: Cache Jest cache
        uses: actions/cache@v1
        id: cache-jest-cache
        with:
            path: .jest-cache
            key: ${{ runner.os }}-${{ matrix.chunk }}-jest
```

And for Jest Cache, we can setup cache in github action.

```
      - name: Cache Jest cache
        uses: actions/cache@v1
        id: cache-jest-cache
        with:
            path: .jest-cache
            key: ${{ runner.os }}-${{ matrix.chunk }}-jest
```

There is no code changes required, it's just setting up the github action with right configurations and how to split the tests into multiple job to run tests in less time.

Here is how jobs execution will look like.

![image](https://user-images.githubusercontent.com/13637803/186611026-1ffc85b4-ea27-4bdb-8add-a54ad62c4608.png)
