### ISSUE TITLE
[$1000] mWeb - Close Account - Scroll bar is black color instead light green

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13592]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to URL https://staging.new.expensify.com/
2. Login with any account
3. Go to Settings > Security > Close Account
4. Enter the any letter and tap Return button
5. Do it until you can see the scroll bar

## Expected Result:
The scroll bar should be light green

## Actual Result:
Scroll bar is black color

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Mobile Web (only Safari)

**Version Number:** 1.2.39.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/207699235-6070cf18-cfcd-4cb4-a64e-f956e249c57a.mp4

**Expensify/Expensify Issue URL:** 

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013fdb138457063279</li>
        <li>Upwork Job ID: 1603397981957001216</li>
        <li>Last Price Increase: 2022-12-15</li>
    </ul>
</details>

**Comment by Delgee** [comment]
### Proposal

If we want to change scrollbar color we can just add this CSS.

```css
textarea {
  scrollbar-width: thin;
  scrollbar-color: #03d47c transparent;
}
textarea::-webkit-scrollbar {
  width: 6px;
}
textarea::-webkit-scrollbar-track {
  background-color: transparent;
}
textarea::-webkit-scrollbar-thumb {
  background-color: #03d47c;
  border-radius: 6px;
  border: 3px solid #03d47c;
}
```

It will work on cross browser.

Ios safari mobile web working example.


![Screenshot 2022-12-15 at 23 31 11](https://user-images.githubusercontent.com/6459339/207901219-52282fd6-5d9e-4f9d-bf6f-c1ad8b4e92fc.png)
