### ISSUE TITLE
[$2000] Feature Request: Update the desktop App to the latest version vs updating one version at a time

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/App#23660]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Problem
When you update the New Expensify desktop App and you’re 2+ versions behind, you have to go through the update flow multiple times to reach the latest version. This is slow and annoying.

## Solution
Always update the App to the latest version

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1690311201014139

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01669625653d9ce2da</li>
        <li>Upwork Job ID: 1685790010288013312</li>
        <li>Last Price Increase: 2023-08-14</li>
    </ul>
</details>

**Comment by neil-marcellini** [comment]
One other thing that's tangentially related, is I think it would be great if we automatically updated the app every time it's opened, just like web.

**Comment by NicMendonca** [comment]
@neil-marcellini are you thinking this is something that would be worked on internally or externally?

**Comment by neil-marcellini** [comment]
I'm pretty sure it can be external. Maybe there's something we need to do on the backend but it's probably 99% front end.

**Comment by jeet-dhandha** [comment]
Can someone point me in the direction on how to simulate the update flow in DEV environment ?

**Comment by jeet-dhandha** [comment]
@neil-marcellini

**Comment by jeet-dhandha** [comment]
> Can someone point me in the direction on how to simulate the update flow in DEV environment ?

@neil-marcellini

**Comment by Christinadobrzyn** [comment]
Hey @jeet-dhandha you can create a test account following the steps in our [contributor guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). Once you have a test account, opening the NewExpensify desktop app > click New Expensify will show you how the Update workflow currently works.

**Comment by neil-marcellini** [comment]
Might want to bump the bounty up, there's been hardly any activity here. I don't know how we can simulate an update off the top of my head, without digging into the code myself.

**Comment by Christinadobrzyn** [comment]
Raised the bounty to $2000 - @neil-marcellini would this be worth reaching out to SWM or others to take this?

**Comment by alexxxwork** [comment]
@neil-marcellini Can't reproduce it on random old versions (tried 1.3.44-2 and 1.2.40-3) - latest version (1.3.50-3 for now) being downloaded. Could you tell any exact version where you see this behaviour?

**Comment by situchan** [comment]
@alexxxwork where did you download random old versions?

**Comment by alexxxwork** [comment]
Some details:
NewExpensify desktop requests https://expensify-cash.s3.amazonaws.com/latest-mac.yml and it contains latest version for now:
```
version: 1.3.50-3
files:
    - url: New Expensify-1.3.50-3-mac.zip
      sha512: 9gQYvnTWIQZv79xIiKHR0l7lADPYo13fw/15H+LGUoEsx9p5dv2tsem4tY2MFogjGrmp5MYZYIQRXKXXOF2BjA==
      size: 105335857
    - url: NewExpensify.dmg
      sha512: p95gCRkgVr8xLWjExR/PdNO1OUeEoEqCZ68eUzg5+9P9kxftNR7RKBaBst9itd+UFxQMq6kOSGfryQrrFKDJQQ==
      size: 109257482
path: New Expensify-1.3.50-3-mac.zip
sha512: 9gQYvnTWIQZv79xIiKHR0l7lADPYo13fw/15H+LGUoEsx9p5dv2tsem4tY2MFogjGrmp5MYZYIQRXKXXOF2BjA==
releaseDate: "2023-08-07T18:27:41.698Z"
```
