### ISSUE TITLE
Optimize `getHitSlopForSize` functionality or remove it

### ISSUE THREAD

**Issue by muttmuure** [Expensify/App#28161]
From here: https://expensify.slack.com/archives/C05LX9D6E07/p1694783353289039 

# Problem

There is an excessive number of layout event subscriptions due to `getHitSlopForSize` functionality. This is added to every single perusable element and results in tons of events being sent from native to react. 

Most of the times these events don’t trigger any updates from our testing yet there is still typically hundrens+ of them being passed with every single update that happens on screen. 

# Solution

Try to disable this functionality (the app should function without it as it only adjust hit slop area of buttons) and then measure the impact.

**Comment by MaciejSWM** [comment]
Hello, I'm Maciej from Software Mansion, an expert agency, and I'll be taking a shot at this.

**Comment by MaciejSWM** [comment]
I got some suggestions from Krzysiek Magiera regarding testing this. He suggests using a tool to measure FPS and interaction time like this one: https://github.com/bamlab/flashlight. Then I create two production builds - one with getHitSlopForSize, one without it, and gather the results.

Also, @muttmuure sorry for the delay, I was asked to focus on https://github.com/Expensify/App/issues/31766. I'll try to prepare the builds in the incoming days.

**Comment by muttmuure** [comment]
Sounds good to me!

**Comment by MaciejSWM** [comment]
I'm back at it today

**Comment by MaciejSWM** [comment]
I'm back with the findings.

What I did:
`hitSlop` is used only in one component in the app, which is the `BaseGenericPressable.tsx`:
```
<Pressable
            hitSlop={shouldUseAutoHitSlop ? hitSlop : undefined}
            onLayout={shouldUseAutoHitSlop ? onLayout : undefined}
```
I commented out the `hitSlop` and `onLayout` props not to run anything on layout changes.

Then I built two versions of the app using `./gradlew assembleDevRelease` command. This resulted in two `.apk` files. One with clean `main` branch, one with `hitSlop` and `onLayout` disabled.

I uploaded both `.apk` files to https://flashlight.dev/ and prepared a testing scenario that scrolls through the app, enters and exits chats, opens the global menu and navigates through tabs in `New Chat` screen.
```
- launchApp
- assertVisible: "DEV"
- swipe:
    start: 57%, 84%
    end: 59%, 33%
    duration: 251
- waitForAnimationToEnd
- tapOn:
    point: "50%,46%"
- waitForAnimationToEnd
- tapOn: "Back"
- waitForAnimationToEnd
- swipe:
    start: 58%,74%
    end: 58%,18%
    duration: 200
- waitForAnimationToEnd
- tapOn:
    point: "50%,46%"
- waitForAnimationToEnd
- tapOn: "Back"
- waitForAnimationToEnd
- swipe:
    start: 56%,81%
    end: 61%,5%
    duration: 284
- waitForAnimationToEnd
- tapOn:
    point: "50%,46%"
- waitForAnimationToEnd
- tapOn: "Back"
- waitForAnimationToEnd
- tapOn: "My settings"
- swipe:
    start: 51%,84%
    end: 51%,54%
    duration: 250
- waitForAnimationToEnd
- tapOn: "Back"
- waitForAnimationToEnd
- tapOn:
    point: 88%,88%
- waitForAnimationToEnd
- tapOn: "Start chat"
- scroll
- tapOn: "Room"
- scroll
- tapOn: "Back"
- waitForAnimationToEnd
- tapOn: "Back"
```

Flashlight used this file to test each `.apk` and measure it's performance. It runs each test 10 times and provides aggregated results.

Here are the results for the clean `main` branch:
https://app.flashlight.dev/report?testRunIds=536679b7-fc91-4e69-b44e-ca828ef4cfc2
![image](https://github.com/Expensify/App/assets/85628901/bbaeaac1-9028-434f-9bfa-64332d4f6e26)

And here are the results for the branch with deleted `hitSlop` and `onLayout` props:
https://app.flashlight.dev/report?testRunIds=5861c1a9-a19b-4b33-a20e-3c750990c001
![image](https://github.com/Expensify/App/assets/85628901/76b53a89-d6dc-43c3-babb-975a089e1a63)

Observations:
- Both `.apk` files scored `61` in the aggregated result
- The FPS, average CPU and average RAM usage was almost identical, with the results from the `main` branch being slightly better (`main` branch is the one with `hitSlop` and `onLayout`).

Conclusion:
- No noticeable negative impact of having `hitSlop` or `onLayout` on the `<Pressable />` component was observed.
