### ISSUE TITLE
[HOLD for payment 2025-01-17] [$250] Code formatting in Help Site needs improvement

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#54227]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** Needs Reproduction
**Reproducible in production?:** Needs Reproduction
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @RachCHopkins 
**Slack conversation** (hyperlinked to channel name): [expensify_bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1734396664491819)

## Action Performed:
Use ` word ` AKA "code" formatting in help doc
## Expected Result:
Text in code format appears tidy and well-defined
## Actual Result:
Code format is a large monotype with no clear delineation
## Workaround:
Unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

![image (13)](https://github.com/user-attachments/assets/e1cd4612-4503-491c-95f4-3ad669d50d42)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021869834819876428961</li>
        <li>Upwork Job ID: 1869834819876428961</li>
        <li>Last Price Increase: 2024-12-26</li>
<li>Automatic offers: </li>
<ul>
<li>shubham1206agra | Contributor | 105506003</li>
<li>JoshIri360 | Contributor | 105540504</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @slafortune</details>

**Comment by MelvinBot** [comment]
This has been labelled "Needs Reproduction". Follow the steps here: https://stackoverflowteams.com/c/expensify/questions/16989

**Comment by RachCHopkins** [comment]
Here's a good example: https://help.expensify.com/articles/expensify-classic/bank-accounts-and-payments/payments/Receive-and-Pay-Bills

**Comment by dubielzyk-expensify** [comment]
I'd love if we could style it like we do in the app:
![CleanShot 2024-12-17 at 15 12 39@2x](https://github.com/user-attachments/assets/5c450ca5-087f-46bf-a2a2-8ad6862a204b)

And use `Expensify Mono` for this as well.

Keen to hear if they other designers agree or not. @Expensify/design

**Comment by dubielzyk-expensify** [comment]
Yeah, I think we should add support for it, but keen to hear if @shawnborton and @dannymcclain agrees. I know it'll add a few kb/mb to the page load

**Comment by shawnborton** [comment]
We should definitely add it there, I'm kind of surprised it doesn't exist there already!

**Comment by shawnborton** [comment]
And I agree with Jon about being consistent with the styles across app & docs.

**Comment by JoshIri360** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The code formatting on the Help Site needs improvement to match the styling used in the app, ensuring consistency across platforms.

### What is the root cause of that problem?
The Help Site does not currently support the Expensify Mono font, leading to inconsistencies in code formatting between the app and the Help Site.

### What changes do you think we should make in order to solve the problem?
1. **Add Expensify Mono Fonts to the docs Fonts folder**

1. **Add Expensify Mono Font Support:**
   - Include the Expensify Mono font in the `_fonts.scss` file.
   ```scss
   @font-face {
     font-family: Expensify Mono;
     font-weight: 400;
     font-style: normal;
     src: url('/assets/fonts/ExpensifyMono-Regular.woff2') format('woff2'), url('/assets/fonts/ExpensifyMono-Regular.woff') format('woff');
   }

   @font-face {
     font-family: Expensify Mono;
     font-weight: 700;
     font-style: normal;
     src: url('/assets/fonts/ExpensifyMono-Bold.woff2') format('woff2'), url('/assets/fonts/ExpensifyMono-Bold.woff') format('woff');
   }
   ```

2. **Update Code Styling:**
   - Modify the code block styling in `_main.scss` to use the Expensify Mono font and ensure it matches the app's styling.
   ```scss
   code {
       font-family: 'Expensify Mono', 'Helvetica Neue', 'Helvetica', Arial, sans-serif;
       border-width: 1px;
       border-style: solid;
       border-radius: 5px;
       border-color: var(--color-borders);
       background-color: var(--color-highlightBG);
       line-height: 20px;
       padding-left: 5px;
       padding-right: 5px;
       font-size: 13px;
       margin-top: 0px;
       margin-bottom: 0px;
   }
   ```
This would make it look like this:
![image](https://github.com/user-attachments/assets/b300d12b-d45b-4dba-b997-8ebbb775e6e1)


### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
1. Verify that the Expensify Mono font is loaded and applied correctly to code blocks on the Help Site.
2. Ensure that the code block styling (background, border, padding) matches the app's styling.

### What alternative solutions did you explore? (Optional)
N/A
