### ISSUE TITLE
[C+ Checklist Needs Completion] [$250] Update Expensify Help version badges to look like badges

### ISSUE THREAD

**Issue by srikarparsi** [Expensify/App#64093]
### Problem

Pages on Expensify Help have badges on the top right to indicate what version (`Expensify Classic` or `New Expensify`) the page is referencing. However, these badges give the impression that they can be clicked since they look like buttons.

### Solution

Update the badge style to look more like a badge. **Note: we only want these to look like badges when the segmented control is missing. This means, when there is only one badge showing to indicate what kind of content there is, we should change the button style to a badge style. If the page can be switched via buttons between New Expensify and Classic, we do not want to change the button style.** 

#### Current:
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/90de4304-f243-4ada-9d85-445329686afb" />

<img width="177" alt="Image" src="https://github.com/user-attachments/assets/9ecd8acf-1cab-4434-ba4a-d92e5a98cc67" />

#### Expected:
<img width="1166" alt="Image" src="https://github.com/user-attachments/assets/5b1f74fe-abbb-42e0-9695-6331b038cbbc" />

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021933213486669999294</li>
        <li>Upwork Job ID: 1933213486669999294</li>
        <li>Last Price Increase: 2025-06-12</li>
<li>Automatic offers: </li>
<ul>
<li>daledah | Contributor | 107716330</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @rojiphil</details>

**Comment by srikarparsi** [comment]
More conversation about this in this [issue](https://github.com/Expensify/App/issues/59349#issuecomment-2783835987)

**Comment by srikarparsi** [comment]
cc @daledah since you created a working concept [here](https://github.com/Expensify/App/issues/59349#issuecomment-2812407138)

**Comment by neonbhai** [comment]
🚨 Edited by **proposal-police**: This proposal was **edited** at 2025-06-12 22:13:22 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update Expensify Help version badges to look like badges

### What is the root cause of that problem?
Feature request

### What changes do you think we should make in order to solve the problem?
The css related to the platform tabs is here:

https://github.com/Expensify/App/blob/06ea630b49c050faf824a97f2ba506217ecc2e37/docs/_sass/_main.scss#L1095-L1131

We will: 
- Remove the background color applied here:
  https://github.com/Expensify/App/blob/06ea630b49c050faf824a97f2ba506217ecc2e37/docs/_sass/_main.scss#L1130
  ```diff
  -background-color: var(--color-button-background);
  ```
- Add these styles when `.active` class is present
  ```css
  #platform-tabs > .active {
      color: var(--color-text);
      border-radius: 0;
      border: 1px solid var(--color-borders);
      cursor: default;
  }
  ```

### [UPDATE] Handling Multiple Buttons

When two buttons are present, we don't want the new styles. We need a way from css to know multiple tabs are present

1. <Details><Summary>First Approach</Summary>
 	- Add a multiple-tabs class in platform-tabs.js [here](https://github.com/Expensify/App/blob/ec5d325386facbcd5cd30b4f835b658cfb96988d/docs/assets/js/platform-tabs.js) 
 	  ```js
 	  // Add a class to indicate when both tabs are present
		if ((expensifyClassicContent || showExpensifyClassicBadge) && 
		    (newExpensifyContent || showNewExpensifyBadge)) {
		    platformTabs.classList.add('multiple-tabs');
		}
		```
 	- Check for this class when applying the new style:
 	  ```css
 	  #platform-tabs:not(.multiple-tabs) > .active {
		    color: var(--color-text);
		    border-radius: 0;
		    border: 1px solid var(--color-borders);
		    cursor: default;
		}
		```
    </Details>

2. <Details><Summary>Second Approach - Check for only child (Recommended) </Summary>
     
    It is cleaner if we simply check if platforms-tabs has only one active child. Final changes applied [here](https://github.com/Expensify/App/blob/06ea630b49c050faf824a97f2ba506217ecc2e37/docs/_sass/_main.scss#L1128-L1131)

    ```css
    #platform-tabs > .active:only-child {
            color: var(--color-text);
            border-radius: 0;
            border: 1px solid var(--color-borders);
            cursor: default;
    }
    ```


    Note: The one child will always have active class (ref: [platform.js](https://github.com/Expensify/App/blob/ec5d325386facbcd5cd30b4f835b658cfb96988d/docs/assets/js/platform-tabs.js))
    
</Details>

### Result
<Details><Summary>Before</Summary>

![Image](https://github.com/user-attachments/assets/3410c480-9dc4-4a7f-aafb-8fbefc7837c2)


</Details>

<Details><Summary>After</Summary>

https://github.com/user-attachments/assets/580cda56-7f46-4d40-bfd7-b3a2c489a327

</Details>

**Comment by shawnborton** [comment]
I updated the OP to be a bit more clear that we only want the badge style for when the page is not controlled by the two buttons that allow the user to switch between platforms.

**Comment by neonbhai** [comment]
Proposal [updated](https://github.com/Expensify/App/issues/64093#issuecomment-2967753262)

**Comment by mobiledeveloper2025** [comment]
Contributor details
Your Expensify account email: mastermern3@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01a41345ad9d209f24

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Pages on Expensify Help have badges on the top right to indicate what version (`Expensify Classic` or `New Expensify`) the page is referencing. However, these badges give the impression that they can be clicked since they look like buttons.
### What is the root cause of that problem?
This is a CSS issue.
In the following file:
https://github.com/Expensify/App/blob/06ea630b49c050faf824a97f2ba506217ecc2e37/docs/_sass/_main.scss#L1119-L1131
We apply button styles (such as `cursor`, `background-color`, `border-radius` ...), which makes the badges appear interactive.

### What changes do you think we should make in order to solve the problem?
1. Update the CSS to resemble badges instead of buttons
    Remove `cursor` and `background-color`.
    Modify `border-radius` and `padding` to match the design in your screenshot.
    Add a `border`
```css
    #platform-tabs > * {
        border-radius: 5px;
        padding: 10px 15px;
        box-sizing: border-box;
        height: 36px;
        line-height: 16px;
        border: 1px solid var(--color-borders);
    }

    #platform-tabs > .active {
        color: var(--color-text);
    }
```
2. Remove the click event from the new badges
    We can remove the code related to badge click events here:
https://github.com/Expensify/App/blob/06ea630b49c050faf824a97f2ba506217ecc2e37/docs/assets/js/main.js#L303-L311

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
 1. Test the badge style for both `Expensify Classic` and `New Expensify`.
 2. Ensure that click events are not triggered when interacting with the badges.
### What alternative solutions did you explore? (Optional)
There are some variable names related to badges, which are still using tab-based logic from the old button implementation.
It might be a good idea to fully refactor this to follow proper badge logic instead.

**Comment by daledah** [comment]
Report my proposal from https://github.com/Expensify/App/issues/59349#issuecomment-2766540238
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Update the badge style to look more like a badge

### What is the root cause of that problem?
New Feature

### What changes do you think we should make in order to solve the problem?

We can modify the tab's visual style (e.g. reduce opacity or add a disabled indicator) when only one tab is present to signal its static nature.

```css
#platform-tabs > .badge{
    border-style: solid;
    border-width: 2px;
    border-color: #17372B; 
    background-color: transparent;
    border-radius: 4px;
    text-align: center;
}
```

Then update the [file](https://github.com/Expensify/App/blob/main/docs/assets/js/platform-tabs.js#L1) as follows:
```
if (expensifyClassicContent || showExpensifyClassicBadge) {
    // ....
    if (!newExpensifyContent) {
        tab.classList.add('badge');
    }
}

if (newExpensifyContent || showNewExpensifyBadge) {
    // ...
    if (!expensifyClassicContent) {
        tab.classList.add('badge');
    }
}

```



### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

None

### What alternative solutions did you explore? (Optional)
