### ISSUE TITLE
[$4000] Long lines in code blocks should not wrap

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#7497]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open app 
2. Send few long lines of code in chat  
```
- name: Decrypt Botify GPG key
        run: cd .github/workflows && gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output OSBotify-private-key.asc OSBotify-private-key.asc.gpg
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
```

## Expected Result:
Long lines in code blocks should not wrap

## Actual Result:
Long lines in code blocks wrap

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Desktop App

**Version Number:** 1.1.33-3
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![Screen Shot 2022-02-01 at 1 10 00 AM](https://user-images.githubusercontent.com/43995119/151920907-c0add7fa-3c7e-4da0-8307-d71e8bbee5db.png)

**Expensify/Expensify Issue URL:**
**Issue reported by:** @roryabraham 
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1643397896087709

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

[view this job](https://www.upwork.com/jobs/~0166d837401b37414a)
